"""
Schedule CEO Briefing to run every Monday at 8 AM
Works on Windows (Task Scheduler), Mac (launchd), Linux (cron)

Usage: python schedule_briefing.py [--remove]
"""

import os
import sys
import platform
import subprocess
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent


def setup_windows_task_scheduler():
    """Set up Windows Task Scheduler to run ceo_briefing.py every Monday 8 AM"""
    script_path = BASE_DIR / "ceo_briefing.py"
    
    print(f"📅 Setting up Windows Task Scheduler...")
    print(f"   Script: {script_path}")
    print(f"   Schedule: Every Monday at 8:00 AM")
    print(f"   Working Directory: {BASE_DIR}")
    
    # Task Scheduler XML template
    task_xml = f'''<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>{datetime.now().isoformat()}</Date>
    <Author>AI-Employee-System</Author>
    <Description>CEO Monday Morning Briefing - Auto-generated by AI Employee</Description>
  </RegistrationInfo>
  <Triggers>
    <CalendarTrigger>
      <StartBoundary>2026-04-28T08:00:00</StartBoundary>
      <ScheduleByWeek>
        <WeeksInterval>1</WeeksInterval>
        <DaysOfWeek>
          <Monday/>
        </DaysOfWeek>
      </ScheduleByWeek>
    </CalendarTrigger>
  </Triggers>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT1H</ExecutionTimeLimit>
    <Priority>5</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>python.exe</Command>
      <Arguments>"{script_path}"</Arguments>
      <WorkingDirectory>{BASE_DIR}</WorkingDirectory>
    </Exec>
  </Actions>
  <Principals>
    <Principal id="Author">
      <UserId>S-1-5-18</UserId>
      <RunLevel>HighestAvailable</RunLevel>
    </Principal>
  </Principals>
</Task>'''

    # Save XML to temporary file
    xml_file = BASE_DIR / "ceo_briefing_task.xml"
    
    try:
        # Write XML file (UTF-16 LE as required by Task Scheduler)
        with open(xml_file, 'w', encoding='utf-16-le') as f:
            f.write(task_xml)
        print(f"✅ XML template created: {xml_file}")
        
        # Register the task
        task_name = "AIEmployee-CEOBriefing"
        cmd = f'schtasks /create /tn "{task_name}" /xml "{xml_file}" /f'
        
        print(f"\n🔧 Registering task with Windows Task Scheduler...")
        result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
        
        if result.returncode == 0:
            print(f"✅ Task '{task_name}' registered successfully!")
            print(f"\n📋 Task Details:")
            print(f"   Name: {task_name}")
            print(f"   Schedule: Every Monday at 8:00 AM")
            print(f"   Action: Run {script_path}")
            print(f"\n📌 To verify, run: schtasks /query /tn \"AIEmployee-CEOBriefing\" /v")
            print(f"📌 To run manually: schtasks /run /tn \"AIEmployee-CEOBriefing\"")
            print(f"📌 To remove: schtasks /delete /tn \"AIEmployee-CEOBriefing\" /f")
            return True
        else:
            print(f"❌ Error registering task:")
            print(result.stderr)
            print(f"\n💡 Troubleshooting:")
            print(f"   1. Make sure you're running as Administrator")
            print(f"   2. Try running: python schedule_briefing.py")
            print(f"   3. Or manually import the XML in Task Scheduler GUI")
            return False
            
    except Exception as e:
        print(f"❌ Failed to set up Task Scheduler: {e}")
        return False


def remove_windows_task():
    """Remove the scheduled task from Windows Task Scheduler"""
    task_name = "AIEmployee-CEOBriefing"
    cmd = f'schtasks /delete /tn "{task_name}" /f'
    
    print(f"Removing task '{task_name}'...")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    
    if result.returncode == 0:
        print(f"✅ Task removed successfully")
        return True
    else:
        print(f"❌ Failed to remove task: {result.stderr}")
        return False


def setup_mac_launchd():
    """Set up launchd on macOS"""
    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.aiemployee.ceo-briefing</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/bin/python3</string>
        <string>{BASE_DIR / 'ceo_briefing.py'}</string>
    </array>
    <key>StartCalendarInterval</key>
    <array>
        <dict>
            <key>Weekday</key>
            <integer>2</integer>
            <key>Hour</key>
            <integer>8</integer>
            <key>Minute</key>
            <integer>0</integer>
        </dict>
    </array>
    <key>WorkingDirectory</key>
    <string>{BASE_DIR}</string>
    <key>StandardOutPath</key>
    <string>{BASE_DIR / 'Logs' / 'briefing.log'}</string>
    <key>StandardErrorPath</key>
    <string>{BASE_DIR / 'Logs' / 'briefing_error.log'}</string>
</dict>
</plist>"""
    
    plist_path = Path.home() / "Library/LaunchAgents/com.aiemployee.ceo-briefing.plist"
    plist_path.parent.mkdir(parents=True, exist_ok=True)
    
    plist_path.write_text(plist_content)
    print(f"✅ launchd plist created at {plist_path}")
    print(f"   Load with: launchctl load {plist_path}")


def setup_linux_cron():
    """Print cron setup instructions for Linux"""
    cron_line = f"0 8 * * 1 cd {BASE_DIR} && /usr/bin/python3 ceo_briefing.py >> {BASE_DIR}/Logs/briefing.log 2>&1"
    
    print("📋 Cron setup instructions for Linux:")
    print(f"   1. Run: crontab -e")
    print(f"   2. Add this line:")
    print(f"      {cron_line}")
    print(f"   3. Save and exit")
    print(f"\n   To verify: crontab -l")


def main():
    print("\n" + "="*70)
    print("🤖 AI EMPLOYEE - CEO BRIEFING SCHEDULER")
    print("="*70)
    
    # Check if --remove flag passed
    if len(sys.argv) > 1 and sys.argv[1] == "--remove":
        if platform.system() == "Windows":
            remove_windows_task()
        else:
            print("Remove function only implemented for Windows. Manual removal needed.")
        return
    
    # Determine OS and set up appropriately
    system = platform.system()
    
    if system == "Windows":
        print(f"\n🖥️  Windows detected - Setting up Task Scheduler")
        success = setup_windows_task_scheduler()
        if success:
            print("\n✨ CEO Briefing will run every Monday at 8:00 AM!")
        else:
            print("\n⚠️  Setup may have failed. Check errors above.")
    
    elif system == "Darwin":
        print(f"\n🍎 macOS detected - Setting up launchd")
        setup_mac_launchd()
        print("\n✨ CEO Briefing will run every Monday at 8:00 AM!")
    
    elif system == "Linux":
        print(f"\n🐧 Linux detected - Cron setup instructions:")
        setup_linux_cron()
    
    else:
        print(f"❌ Unsupported OS: {system}")
        return
    
    # Verify ceo_briefing.py exists
    briefing_script = BASE_DIR / "ceo_briefing.py"
    if not briefing_script.exists():
        print(f"\n⚠️  Warning: {briefing_script} not found!")
    else:
        print(f"\n✅ Briefing script verified: {briefing_script}")
    
    print("\n" + "="*70)
    print("Setup complete! Next briefing will run on Monday at 8:00 AM")
    print("="*70 + "\n")


if __name__ == "__main__":
    main()
